[tool.poetry]
name = "hpcp-assignment"
version = "0.1.0"
description = ""
authors = [
  "Lukas Breiter <lukas.breiter@students.fhnw.ch>",
  "Christoph Elmiger <christoph.elmiger@students.fhnw.ch>",
  "Mikaela Buzdin <mikaela.buzdin@students.fhnw.ch>",
]
readme = "README.md"

[[tool.poetry.packages]]
include = "src"

[tool.poetry.dependencies]
python = ">=3.12"
numpy = "<2.3"
threadpoolctl = "^3.6.0"
tqdm = "^4.67.1"
pyyaml = "^6.0.2"
dask = { version = "^2025.9.0", extras = ["distributed"] }
bokeh = ">=3.1.0"
numba = "^0.61.2"
scikit-learn = "^1.7.1"
mpi4py = "^4.1.0"
sglang = "^0.5.2"
pybase64 = "^1.4.2"
pydantic = "^2.11.9"
resource = "^0.2.1"
cupy-cuda12x = "^13.6.0"
pyinstrument = "^5.1.1"
pip = "^25.2"
ipykernel = "^6.30.1"
dask-jobqueue = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"
ruff = "^0.12.11"
line-profiler = "^5.0.0"

[tool.poetry.group.notebooks.dependencies]
notebook = ">=7.4.5,<8.0.0"
ipykernel = ">=6.30.1,<7.0.0"
ipywidgets = "^8.1.7"
matplotlib = "^3.10.6"
mpl-animators = ">=1.2.0"
jupyter = "^1.1.1"

[tool.poetry.group.profiling]
optional = true

[tool.poetry.group.profiling.dependencies]
# NVTX python bindings (optional). Install with:
#   poetry install --with profiling
# Only imported when MULTIGPU_NVTX=1
nvtx = "^0.2.10"

[tool.poetry.group.data.dependencies]
pandas = "^2.3.2"
xarray = "^2025.9.0"
zarr = "^3.1.2"
numcodecs = "^0.16.2"
h5py = "^3.14.0"
lxml = "^6.0.1"
zeep = "^4.3.1"
drms = "^0.9.0"
reproject = "^0.15.0"
astropy = "^7.1.0"
sunpy = "^7.0.1"
aiapy = "^0.10.1"
sunkit-instruments = "^0.6.2"
chiantipy = "^0.15.2"

[tool.poetry.scripts]
hpcp-baseline  = "src.baseline.main:main"
hpcp-dask      = "src.dask.main:main"
hpcp-singlegpu = "src.singlegpu.main:main"
hpcp-multigpu  = "src.multigpu.main:main"
verify = "src.common.verification.cli:main"

[tool.ruff]
# Ignore these paths for both lint and format
extend-exclude = [
  "src/baseline/vendor/",
  "build/",
  "dist/",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
